####SUN BASED####
- !include automation/sunset_frontporch.yaml
- !include automation/sunrise_frontporch.yaml

####TIME BASED####
- !include automation/time_evening_couchlamp_off.yaml
- !include automation/time_evening_couchlamp_on.yaml
- !include automation/time_morning_couchlamp_off.yaml
- !include automation/time_morning_couchlamp_on.yaml
