homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_loc_home
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_password

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  api_password: !secret api_password

zone:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  radius: 60
  icon: mdi:account-multiple

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarmcom_username
  password: !secret alarmcom_password

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key

# Devices #
sensor: !include sensors.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    consider_home: 0:03:00

# Track the sun
sun:

- platform: squeezebox
  host: 192.168.0.15
  port: 9002

input_boolean:
  disable_outdoor_lights_automation:
    name: Disable the outdoor lights automation
    initial: off
    icon: mdi:track-light

panel_iframe:
  nodered_flows:
    title: 'Node-RED Flows'
    url: 'http://hassio.local:1880'
    icon: mdi:nodejs
    
emulated_hue:
  expose_by_default: false
  exposed_domains:
    - light
    - switch
    - group
  entities:
    group.all_lights:
      name: "All Lights"
      hidden: false
    group.downstairs_lights:
      name: "Downstairs"
      hidden: false
    group.upstairs_lights:
      name: "Upstairs"
      hidden: false
    group.xmas_lights:
      name: "Xmas"
      hidden: false
    group.landscape_lights:
      name: "Landscape"
      hidden: false
    group.fireplace_lights:
      name: "Fireplace"
      hidden: false
    group.outside_lights:
      name: "Outside Lights"
      hidden: false
    group.back_porch_sensors:
      hidden: true
    group.family_room_lights:
      name: "Family Room Lights"
      hidden: false
    light.level_2:
      name: "Front Porch"
      hidden: false
    light.level_3:
      name: "Master Sitting"
      hidden: false
    light.level_4:
      name: "Upstairs Hall"
      hidden: false
    light.level_6:
      name: "Downstairs Hall"
      hidden: false
    light.level_5:
      name: "Backporch"
      hidden: false
    switch.switch_3:
      name: "Landscape Back"
      hidden: false
    switch.switch_4:
      name: "Landscape Front"
      hidden: false
    light.couch_lamp:
      hidden: true
    light.family_floor_lamp:
      hidden: true
    light.fireplace_left:
      hidden: true
    light.fireplace_right:
      hidden: true
    light.family_room:
      hidden: true
    group.family_room:
      hidden: true
    group.driveway_lights:
      hidden: true

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include_dir_merge_named group
automation: !include automations.yaml
script: !include scripts.yaml
