homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_loc_home
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  #customize: !include customize.yaml

mqtt:
  broker: 192.168.0.25
  username: !secret mqtt_user
  password: !secret mqtt_password

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

frontend:
  themes: !include themes.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

mobile_app:

config:

cloud:

# Track the sun
sun:

system_health:

recorder:
  purge_keep_days: 90

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key

#person:
#  - name: Mike
#    id: c6b7a1d776fd47548e6995dff4147a00
#    device_trackers:
#      - device_tracker.mikes_phone

#device_tracker:
#  - platform: google_maps
#    username: !secret google_username
#    password: !secret google_password

zone:
  - name: Home
    latitude: !secret latitude_loc_home
    longitude: !secret longitude_loc_home
    radius: 60
    icon: mdi:account-multiple
  - name: Work
    latitude: !secret latitude_loc_work
    longitude: !secret longitude_loc_work
    radius: 60
    icon: mdi:account-multiple

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarmcom_username
  password: !secret alarmcom_password

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

# Text to speech
tts:
  - platform: google_translate

http:
  base_url: http://192.168.0.56:8123

# Devices #
sensor: !include sensors.yaml

# Internet Speed Test
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

roku:
  - host: 192.168.0.210
  - host: 192.168.0.66
  #- host: 192.168.0.96 

media_player:
  - platform: squeezebox
    host: 192.168.0.15
    port: 9002

alexa_media:
  accounts:
    - email: !secret alexa_username
      password: !secret alexa_password
      url: "amazon.com"

input_boolean:
  disable_outdoor_lights_automation:
    name: Disable the outdoor lights automation
    initial: off
    icon: mdi:track-light
  loop_halloween_video:
    name: Loop the Halloween Video
    initial: off
    icon: mdi:toggle-switch
  disable_halloween_motion_sensor:
    name: Disable Halloween Sensors
    initial: off
    icon: mdi:toggle-switch
  laugh_1_left:
    name: Laugh 1 Left
    initial: off
    icon: mdi:toggle-switch
  laugh_2_left:
    name: Laugh 2 Left
    initial: off
    icon: mdi:toggle-switch
  laugh_1_right:
    name: Laugh 1 Right
    initial: off
    icon: mdi:toggle-switch
  laugh_2_right:
    name: Laugh 2 Right
    initial: off
    icon: mdi:toggle-switch
  zombie_thriller:
    name: Zombie Thriller
    initial: off
    icon: mdi:toggle-switch

#emulated_hue:
#  expose_by_default: false
#  exposed_domains:
#    - light
#    - switch
#    - group
#  entities:
#    group.all_lights:
#      name: "All Lights"
#      hidden: false
#    group.downstairs_lights:
#      name: "Downstairs"
#      hidden: false
#    group.upstairs_lights:
#      name: "Upstairs"
#      hidden: false
#    group.xmas_lights:
#      name: "Xmas"
#      hidden: false
#    group.landscape_lights:
#      name: "Landscape"
#      hidden: false
#    group.fireplace_lights:
#      name: "Fireplace"
#      hidden: false
#    group.outside_lights:
#      name: "Outside Lights"
#      hidden: false
#    group.back_porch_sensors:
#      hidden: true
#    group.family_room_lights:
#      name: "Family Room Lights"
#      hidden: false
#    light.front_porch_level:
#      name: "Front Porch"
#      hidden: false
#    light.master_sitting_level:
#      name: "Master Sitting"
#      hidden: false
#    light.upstairs_hall_level:
#      name: "Upstairs Hall"
#      hidden: false
#    light.downstairs_hall_level:
#      name: "Downstairs Hall"
#      hidden: false
#    light.back_porch_level:
#      name: "Backporch"
#      hidden: false
#    switch.landscape_back:
#      name: "Landscape Back"
#      hidden: false
#    switch.landscape_front:
#      name: "Landscape Front"
#      hidden: false
#    light.couch_lamp:
#      hidden: true
#    light.family_floor_lamp:
#      hidden: true
#    light.fireplace_left:
#      hidden: true
#    light.fireplace_right:
#      hidden: true
#    light.family_room:
#      hidden: true
#    group.family_room:
#      hidden: true
#    group.driveway_lights:
#      hidden: true

lovelace:
  mode: yaml

influxdb:
  host: 192.168.0.56
  include:
    entities:
      - sensor.single_garage_humidity
      - sensor.single_garage_temperature
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.processor_use
      - sensor.memory_free
      - sensor.master_bath_sensor_temperature
      - sensor.master_bath_sensor_light_level
      - binary_sensor.master_bath_sensor_motion
      - binary_sensor.keezer_fan
      - light.keezer_light
      - sensor.home_to_work
      - sensor.keezer_bottom_temperature
      - sensor.keezer_top_temperature
      - sensor.keezer_exterior_temperature
      - sensor.keezer_average_temperature
      - binary_sensor.keezer_compressor
    domains:
      - sensor
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature

binary_sensor:
  - platform: mqtt
    name: "Keezer Motion"
    state_topic: "/home/keezer/1/motion/value"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Keezer Fan"
    state_topic: "/home/keezer/1/fan/value"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Keezer Compressor"
    state_topic: "/home/keezer/1/compressor/value"
    payload_on: "1"
    payload_off: "0"

light:
  - platform: mqtt
    name: "Keezer Light"
    state_topic: "/home/keezer/1/light/value"
    command_topic: "/home/keezer/1/light/set"
    payload_on: "1"
    payload_off: "0"
    optimistic: false

light:
  - platform: group
    name: "Fireplace Lights"
    entities:
      - light.fireplace_left
      - light.fireplace_right

hue:
  bridges:
    - host: 192.168.0.24

group: !include_dir_merge_named group
automation: !include automations.yaml
#script: !include scripts.yaml
