homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data
  elevation: !secret elevation_loc_home
  
  unit_system: imperial
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Indiana/Indianapolis
  customize: !include customize.yaml

zone:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  radius: 60
  icon: mdi:account-multiple

http:
  api_password: !secret api_password
  cors_allowed_origins:
    - 192.168.0.44
    - http://localhost
    - http://localhost:4201
    - http://localhost:3000
    - home-assistant.io

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry
  
zwave:
  usb_path: /dev/ttyUSB0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarmcom_username
  password: !secret alarmcom_password

##############
#  Includes  #
##############

# Devices #
#alexa: !include alexa.yaml
group: !include groups.yaml
device_tracker: !include device_trackers.yaml
media_player: !include media_players.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automation
notify: !include notify.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml

##############
#  Enables   #
##############
logger: !include loggers.yaml
history:
# Discover some devices automatically
discovery:
sun:
# Allows you to issue voice commands from the frontend
conversation:
# View all events in a logbook
logbook:
# Enables the frontend
frontend:
# Checks for available updates
updater:
# Record
recorder:
  purge_days: 30

emulated_hue:
#  host_ip: 192.168.0.25
#  listen_port: 8300
#  off_maps_to_on_domains:
#    - script
#    - scene
#  type: alexa
  expose_by_default: false
#  exposed_domains:
#    - light
#    - switch

# Text to speech
tts:
  platform: google





