# Weather Prediction
- platform: yr

# Internet Speed Test
- platform: speedtest
  monitored_conditions:
    - download
    - upload

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: mqtt
  name: Single Garage Door
  sensor_class: opening
  payload_on: open
  payload_off: closed
  state_topic: "ha/garage/single/door/state"
  command_topic: "ha/garage/single/door/set"
  retain: true

- platform: mqtt
  name: Double Garage Door
  sensor_class: opening
  payload_on: open
  payload_off: closed
  state_topic: "ha/garage/double/door/state"
  command_topic: "ha/garage/double/door/set"
  retain: true
