- platform: mqtt
  name: Single Garage Temperature
  unit_of_measurement: "°F"
  state_topic: "/home/garage/1/temp/state"

- platform: mqtt
  name: Single Garage Humidity
  unit_of_measurement: "%"
  state_topic: "/home/garage/1/humidity/state"

- platform: mqtt
  name: Keezer Top Temperature
  unit_of_measurement: "°F"
  state_topic: "/home/keezer/1/temp/top"

- platform: mqtt
  name: Keezer Bottom Temperature
  unit_of_measurement: "°F"
  state_topic: "/home/keezer/1/temp/bottom"

- platform: mqtt
  name: Keezer Exterior Temperature
  unit_of_measurement: "°F"
  state_topic: "/home/keezer/1/temp/exterior"

- platform: mqtt
  name: Keezer Average Temperature
  unit_of_measurement: "°F"
  state_topic: "/home/keezer/1/temp/avg"

- platform: google_wifi

- platform: google_travel_time
  name: Home to Work
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.work

- platform: google_travel_time
  name: Work to Home
  api_key: !secret google_api_key
  origin: zone.work
  destination: zone.home

#- platform: hue
#  ip_address: 192.168.0.24
#  token: !secret hue_hub_password

- platform: darksky
  api_key: !secret dark_sky_api_key
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - temperature
    - temperature_low
    - temperature_high
    - apparent_temperature
    - apparent_temperature_low
    - apparent_temperature_high
    - wind_speed
    - wind_bearing
    - daily_summary
    - hourly_summary
    - dew_point
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone

