resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=2
    type: js
views:
  - id: 07B07FF1-245F-4947-A06D-F9FB1D2F94BB
    name: Home
    icon: mdi:home
    theme: PmxMononight
    cards:
      - title: Mint Hill Forecast
        type: custom:dark-sky-weather-card
        entity_sun: sun.sun
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_current_conditions: sensor.dark_sky_icon
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_temperature: sensor.dark_sky_temperature
        entity_visibility: sensor.dark_sky_visibility
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5
      - id: 0BA10E2D-EB65-4397-ACA6-BE027C973ED4 
        type: entity-filter
        entities:
          - media_player.family_room
        state_filter:
          - playing
          - paused
        show_empty: false
        card:
          type: media-control
          entity: media_player.family_room
      - id: C02BED99-A0D6-4C88-AF6E-81BEFE1EA841
        type: entity-filter
        entities:
          - media_player.garage
        state_filter:
          - playing
          - paused
        show_empty: false
        card:
          type: media-control
          entity: media_player.garage
      - id: 3270DCE9-0586-42DB-AB73-5E5659AA2EE4
        type: entity-filter
        entities:
          - media_player.patio
        state_filter:
          - playing
          - paused
        show_empty: false
        card:
          type: media-control
          entity: media_player.patio
      - id: 9D9A94BF-FE60-4153-AC16-44EDDA57F529
        type: entity-filter
        entities:
          - media_player.lr
        state_filter:
          - playing
          - paused
        show_empty: false
        card:
          type: media-control
          entity: media_player.lr
      - id: DDDAB673-F62A-4FE8-9041-3E404B3994E4
        type: entity-filter
        entities:
          - media_player.mb
        state_filter:
          - playing
          - paused
        show_empty: false
        card:
          type: media-control
          title: Master Bedroom
          entity: media_player.mb
      - id: 23851509-D8BD-4A2C-910B-E5A1D258A6DF
        type: entity-filter
        entities:
          - media_player.roku_patio
        state_filter:
          - playing
          - paused
        show_empty: false
        card:
          type: media-control
          entity: media_player.roku_patio
      - id: B9C01776-1AF5-4BB1-89AF-45E067C061B4
        type: alarm-panel
        title: House Alarm
        entity: alarm_control_panel.alarmcom
      - id: 610DF73A-1E0D-4FAB-9F12-1AB8CD6C8429
        type: entities
        title: Drive Time
        show_header_toggle: true
        entities:
          - entity: sensor.home_to_work
            secondary_info: duration
  - id: B303B844-4546-4250-9254-18B7CCE333CD
    title: Lights
    icon: mdi:lightbulb
    cards:
      - id: 48675D17-EA3A-44EF-A4B3-9645742522FB
        type: entities
        title: Family Room
        entities: 
          - entity: light.family_floor_lamp
            name: Floor
          - entity: light.couch_lamp
            name: Couch
          - entity: light.downstairs_hall_level
            name: Hall
          - entity: group.fireplace_lights
            name: Fireplace
      - id: 242F4C38-9F40-4C6D-BE1C-9E290F0A470B
        type: entities
        title: Outside
        entities: 
          - entity: light.driveway
            name: Driveway
          - entity: switch.landscape_back
            name: Landscape Back
          - entity: switch.landscape_front
            name: Landscape Front
          - entity: light.front_porch_level
            name: Front Porch
      - id: 0258202A-AC18-4546-8267-90C76F9D25B0
        type: entities
        title: Back Porch
        entities: 
          - entity: light.back_porch_level
            name: Patio
      - id: BDD71E3D-6AD3-49AC-8BDD-841B41A7E175
        type: entities
        title: Master Bedroom
        entities: 
          - entity: light.master_sitting_level
            name: Sitting
          - entity: light.master_bath_closet
            name: Bathroom Closet
      - id: 44D32019-DC74-4EA3-B0A0-D2C3952ACE55
        type: entities
        title: Upstairs
        entities: 
          - entity: light.upstairs_hall_level
            name: Hall
  - id: DCC0187E-4435-4C69-A1B0-3CBA1D2D65CB
    name: Sensors
    icon: mdi:chart-areaspline
    cards:
      - type: sensor
        entity: sensor.single_garage_temperature
        name: Garage
        height: 75
        line_color: "#3498db"
      - type: sensor
        entity: sensor.dark_sky_apparent_temperature
        name: !secret city_loc_home
