resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=2
    type: js
views:
  - title: Home
    icon: mdi:home
    badges: 
      - sensor.home_to_work
      - sensor.work_to_home
      - sensor.keezer_exterior_temperature
      - sensor.single_garage_temperature
      - sensor.keezer_average_temperature
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.alarm_com
      - type: weather-forecast
        entity: weather.dark_sky
      - type: conditional
        conditions:
          - entity: cover.single_garage_door
            state_not: open
        card: 
          type: glance
          title: Garage Doors
          entities:
            - cover.single_garage_door
      - type: entities
        title: Family Room
        entities:
          - entity: light.couch_lamp
          - entity: light.family_floor_lamp
          - entity: light.fireplace_lights
          - entity: light.downstairs_hall_ceiling
      - type: entities
        title: Master Bedroom
        entities:
          - entity: light.master_bath_closet
          - entity: light.master_sitting_ceiling
      - type: entities
        title: Back Porch
        entities:
          - entity: light.back_porch_ceiling
          - entity: switch.landscape_back_light
      - type: entities
        title: Upstairs
        entities:
          - entity: light.upstairs_hall_ceiling
      - type: entities
        title: Outside
        entities:
          - entity: light.driveway
          - entity: light.front_porch_ceiling
          - entity: switch.landscape_back_light
          - entity: switch.landscape_front_light
  - title: Lights
    icon: mdi:lightbulb
    cards:
      - type: vertical-stack
        cards:
          - type: light
            entity: light.couch_lamp
          - type: light
            entity: light.family_floor_lamp
          - type: light
            entity: light.downstairs_hall_ceiling
          - type: light
            entity: light.fireplace_lights
      - type: vertical-stack
        cards:
          - type: light
            entity: light.upstairs_hall_ceiling
      - type: vertical-stack
        cards:
          - type: light
            entity: light.front_porch_ceiling
          - type: light
            entity: light.back_porch_ceiling
          - type: light
            entity: light.driveway
      - type: vertical-stack
        cards:
          - type: light
            entity: light.master_bath_closet
          - type: light
            entity: light.master_sitting_ceiling
      - type: glance
        title: Landscape Lights
        entities:
        - entity: switch.landscape_back_light
          name: Back
          tap_action:
            action: toggle
        - entity: switch.landscape_front_light
          name: Front
          tap_action:
            action: toggle
  - title: Media
    icon: mdi:filmstrip
    cards:
      - type: media-control
        entity: media_player.family_room
      - type: media-control
        entity: media_player.garage
      - type: media-control
        entity: media_player.master_roku
      - type: media-control
        entity: media_player.patio_roku
      - type: media-control
        entity: media_player.kitchen_echo
      - type: media-control
        entity: media_player.master_bath_echo
  - title: Sensors
    icon: mdi:chart-areaspline
    cards:
      - type: sensor
        entity: sensor.dark_sky_temperature
        graph: line
      - type: sensor
        entity: sensor.single_garage_temperature
        graph: line
      - type: sensor
        entity: sensor.keezer_exterior_temperature
        graph: line
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.keezer_top_temperature
            graph: line
          - type: sensor
            entity: sensor.keezer_average_temperature
            graph: line
          - type: sensor
            entity: sensor.keezer_bottom_temperature
            graph: line
      - type: sensor
        entity: sensor.master_bath_sensor_temperature
        graph: line
      - type: sensor
        entity: sensor.single_garage_humidity
        graph: line
