- alias: front_porch_off_before_sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:15:00"
  action:
    service: homeassistant.turn_off
    entity_id: group.front_porch_lights

- alias: front_porch_on_after_sunset
  trigger:
    platform: sun
    event: sunset
    offset: "00:15:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.front_porch_lights
    data:
      brightness: 50
