- alias: couch_lamp_on_morning_timer
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.couch_lamp_level_3_0

- alias: couch_lamp_off_morning_timer
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '10:30:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.couch_lamp_level_3_0

- alias: couch_lamp_on_evening_timer
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '17:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.couch_lamp_level_3_0

- alias: couch_lamp_off_evening_timer
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.couch_lamp_level_3_0
