- alias: Turn on back porch lights when there is motion
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6_10
      from: '0'
      to: '8'
  action:
    service: homeassistant.turn_on
    entity_id: script.back_porch_lights_on_with_timer_off